Comando,Posicao,Direcao,Sensor Esquerdo,Sensor Frente,Sensor Direito,Compartimento
LIGAR,"(0, 7)",2,PAREDE,PAREDE,VAZIO,PAREDE,SEM CARGA
INFO,"(0, 7)",2,Iniciando busca pelo humano,SEM CARGA
A,"(1, 7)",2,VAZIO,VAZIO,VAZIO,PAREDE,SEM CARGA
A,"(2, 7)",2,VAZIO,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 7)",2,VAZIO,PAREDE,PAREDE,VAZIO,SEM CARGA
G,"(3, 7)",3,VAZIO,PAREDE,PAREDE,VAZIO,SEM CARGA
A,"(3, 6)",3,PAREDE,VAZIO,PAREDE,VAZIO,SEM CARGA
A,"(3, 5)",3,VAZIO,VAZIO,PAREDE,PAREDE,SEM CARGA
G,"(3, 5)",0,VAZIO,VAZIO,PAREDE,PAREDE,SEM CARGA
A,"(2, 5)",0,VAZIO,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(1, 5)",0,PAREDE,PAREDE,VAZIO,VAZIO,SEM CARGA
G,"(1, 5)",1,PAREDE,PAREDE,VAZIO,VAZIO,SEM CARGA
G,"(1, 5)",2,PAREDE,PAREDE,VAZIO,VAZIO,SEM CARGA
G,"(1, 5)",3,PAREDE,PAREDE,VAZIO,VAZIO,SEM CARGA
A,"(1, 4)",3,PAREDE,VAZIO,PAREDE,VAZIO,SEM CARGA
A,"(1, 3)",3,PAREDE,VAZIO,VAZIO,VAZIO,SEM CARGA
G,"(1, 3)",0,PAREDE,VAZIO,VAZIO,VAZIO,SEM CARGA
G,"(1, 3)",1,PAREDE,VAZIO,VAZIO,VAZIO,SEM CARGA
G,"(1, 3)",2,PAREDE,VAZIO,VAZIO,VAZIO,SEM CARGA
A,"(2, 3)",2,VAZIO,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 3)",2,VAZIO,PAREDE,PAREDE,VAZIO,SEM CARGA
G,"(3, 3)",3,VAZIO,PAREDE,PAREDE,VAZIO,SEM CARGA
A,"(3, 2)",3,PAREDE,VAZIO,PAREDE,VAZIO,SEM CARGA
A,"(3, 1)",3,PAREDE,VAZIO,VAZIO,PAREDE,SEM CARGA
G,"(3, 1)",0,PAREDE,VAZIO,VAZIO,PAREDE,SEM CARGA
G,"(3, 1)",1,PAREDE,VAZIO,VAZIO,PAREDE,SEM CARGA
G,"(3, 1)",2,PAREDE,VAZIO,VAZIO,PAREDE,SEM CARGA
A,"(4, 1)",2,VAZIO,PAREDE,HUMANO,PAREDE,SEM CARGA
INFO,"(4, 1)",2,"Humano encontrado, iniciando coleta",SEM CARGA
P,"(4, 1)",2,VAZIO,PAREDE,VAZIO,PAREDE,COM HUMANO
INFO,"(4, 1)",2,Humano coletado,COM HUMANO
INFO,"(4, 1)",2,"Humano coletado, retornando a saida",COM HUMANO
ERRO,"(4, 1)",2,'RoboResgate' object has no attribute 'retornar_saida',"Traceback (most recent call last):
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 40, in executar_resgate
    self.retornar_saida()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoboResgate' object has no attribute 'retornar_saida'
",SEM CARGA
ERRO_FATAL,"(4, 1)",2,'RoboResgate' object has no attribute 'retornar_saida',"Traceback (most recent call last):
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\main.py"", line 24, in main
    robo.executar_resgate()
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 40, in executar_resgate
    self.retornar_saida()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'RoboResgate' object has no attribute 'retornar_saida'
",SEM CARGA
